spring:
  cloud:
    stream:
      defaultBinder: kafka
      bindings:
        input:
          destination: messages
          content-type: application/json
        output:
          destination: filtered
          content-type: application/json
      kafka:
        binder:
          brokers: ${SERVICE_REGISTRY_HOST:127.0.0.1}
          zkNodes: ${SERVICE_REGISTRY_HOST:127.0.0.1}
          defaultZkPort: 2181
          defaultBrokerPort: 9092
server:
  port: 0