---
spring.profiles.active: native
spring.application.name: config-server
server.port: 8888
eureka.client.serviceUrl.defaultZone : http://eureka:8010/eureka/,http://localhost:8011/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/apssouza22/java-microservice
          searchPaths: config-data
        # "native" is used when the native profile is active, for local tests with a classpath repo:
        native:
          searchLocations: classpath:offline-repository/

          
